from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name = 'index'),
    path('register',views.register,name = 'register'),
    path('login',views.login,name = 'login'),
    path('logout',views.logout,name = 'logout'),
    path('services',views.services,name = 'services'),
    path('about',views.about,name = 'about'),
    path('contact',views.contact,name = 'contact'),
    path('check/',views.check,name = 'check'),
    path('check/late_request',views.late_request,name = 'late_request'),
    path('mark__night_attendence',views.mark__night_attendence,name = 'mark__night_attendence'),
    path('meal',views.meal,name="meal"),
    path('adminLogin',views.adminLogin,name='adminLogin'),
    path('leave',views.leave,name = "leave"),
    path('coepMess',views.coepMess,name="coepMess"),
    path('Rector',views.Rector,name = 'rector'),
    path('approveLateRequest',views.approveLateRequest,name = 'approveLateRequest'),
    path('AttendenceReport',views.AttendenceReport,name = 'AttendenceReport'),
    path('getAttendence_report',views.getAttendence_report,name = "getAttendence_report"),
    path('details',views.details,name = 'details'),
    path('details_reg',views.details_reg,name = 'details_reg'),
    path('getdetails',views.getdetails,name='getdetails'),
    path('book_laundry/', views.book_laundry, name='book_laundry'),
    path('booking_success/<int:booking_id>/', views.booking_success, name='booking_success'),
    path('admin_view/', views.admin_view, name='admin_view'),
    path('mark_as_completed/<int:booking_id>/', views.mark_as_completed, name='mark_as_completed'),
    path('completed_laundry/', views.completed_laundry, name='completed_laundry'),
    path('notices/', views.notices, name='notices'),
    path('create_notice/', views.create_notice, name='create_notice'),
    path('booking_status/', views.booking_status, name='booking_status'),
    path('change_meal',views.change_meal,name = 'change_meal'),
    path('meal_status',views.meal_status,name = 'meal_status'),
    path('meal_history',views.meal_history,name='meal_history'),
    path('historyCheck',views.historyCheck,name="historyCheck"),
    path('studentBills',views.studentBills,name = 'studentBills'),
    path('checkBill',views.checkBill,name = 'checkBill'),
    path('createBills',views.createBills,name = "createBills"),
    path('createdBills',views.createdBills,name = 'createdBills'),
]