# Generated by Django 4.2.10 on 2024-03-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_meal_date_remove_meal_name_meal_day_of_week_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='is_attending',
            new_name='is_attending_morning',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='meal_name',
            new_name='morning_meal_name',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='meal',
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_attending_night',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='room',
            field=models.IntegerField(default=205),
        ),
        migrations.AddField(
            model_name='meal',
            name='dinner_meal_name',
            field=models.CharField(default='bcd', max_length=100),
        ),
        migrations.DeleteModel(
            name='CheckInOut',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
