# Generated by Django 4.2.10 on 2024-03-05 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
