# Generated by Django 4.2.10 on 2024-03-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_meal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feature',
        ),
    ]
