# Generated by Django 4.2.10 on 2024-04-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_meal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='day_of_week',
            field=models.CharField(default='Mon', max_length=10),
        ),
    ]
