# Generated by Django 4.2.10 on 2024-04-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_checkinout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinout',
            name='student_name',
            field=models.CharField(default='abd', max_length=50),
        ),
    ]
