# Generated by Django 4.2.10 on 2024-04-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_checkinout_is_checked_checkinout_is_checked_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinout',
            name='check_in_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='checkinout',
            name='check_out_time',
            field=models.DateTimeField(default=None),
        ),
    ]
