# Generated by Django 4.2.10 on 2024-04-02 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_checkinout_check_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinout',
            name='check_in_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 2, 10, 46, 30, 399221, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='checkinout',
            name='check_out_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 2, 10, 46, 30, 399232, tzinfo=datetime.timezone.utc)),
        ),
    ]
