# Generated by Django 4.2.10 on 2024-04-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_checkinout_student_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinout',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='checkinout',
            name='check_out_time',
        ),
    ]
