# Generated by Django 4.2.10 on 2024-04-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_checkinout_check_in_time_checkinout_check_out_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckInOut',
        ),
    ]
