# Generated by Django 4.2.10 on 2024-04-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_maintenancerequest_feedback_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('room', models.IntegerField(default=205)),
                ('misno', models.IntegerField(default=612203048)),
                ('collegemailid', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=150)),
                ('contactno', models.IntegerField(verbose_name=10)),
                ('Yearofstudy', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='feature',
        ),
    ]
