# Generated by Django 4.2.10 on 2024-04-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='details',
        ),
        migrations.AddField(
            model_name='student',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='mess_token',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
