# Generated by Django 4.2.10 on 2024-04-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contactno',
            field=models.IntegerField(verbose_name=20),
        ),
    ]
