# Generated by Django 4.2.10 on 2024-04-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_alter_student_contactno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contactno',
            field=models.IntegerField(default=612203048),
        ),
    ]
