# Generated by Django 4.2.10 on 2024-04-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_messbills'),
    ]

    operations = [
        migrations.AddField(
            model_name='messbills',
            name='month_name',
            field=models.CharField(default='abc', max_length=20),
        ),
    ]
