# Generated by Django 4.2.10 on 2024-04-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_messbills_month_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='month',
            field=models.IntegerField(default=0),
        ),
    ]
