# Generated by Django 4.2.10 on 2024-04-08 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0048_attendance_is_penalty_morning_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NightAttendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.IntegerField(default=205)),
                ('is_marked', models.BooleanField(default=True)),
                ('time', models.DateTimeField(blank=True, default=None, null=True)),
                ('student_name', models.CharField(default='User', max_length=50)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CheckInOut',
        ),
    ]
