# Generated by Django 4.2.10 on 2024-04-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_nightattendence_delete_checkinout'),
    ]

    operations = [
        migrations.AddField(
            model_name='nightattendence',
            name='date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
