# Generated by Django 4.2.10 on 2024-04-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_nightattendence_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nightattendence',
            name='student_name',
        ),
        migrations.AddField(
            model_name='nightattendence',
            name='misno',
            field=models.IntegerField(default=205),
        ),
    ]
