# Generated by Django 4.2.10 on 2024-04-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_remove_nightattendence_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightattendence',
            name='misno',
            field=models.CharField(default='612203048', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='misno',
            field=models.CharField(default='612203048', max_length=30),
        ),
    ]
