# Generated by Django 4.2.10 on 2024-04-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_remove_nightattendence_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightattendence',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
