# Generated by Django 4.2.10 on 2024-04-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_alter_nightattendence_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='laterequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('misno', models.CharField(default='612203048', max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('outgoingTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('IncomingTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('reason', models.CharField(default='612203048', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='nightattendence',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
    ]
